### PR TITLE
Implement partial-payment-page

### PR DESCRIPTION
**Pull request by Khadeeejah**
Implemented the ui for partial-payment page
Created a sub-menu route in the side-bar

issue #31

### CODE REVIEW

**Review by MeisterJustice — CHANGES_REQUESTED** [review]
resolve conflict please

**Comment by Khadeeejah** [comment]
@MeisterJustice  resolved

**Comment by MeisterJustice** [comment]
Is this connected in the sidebar? cos it's not showing up when i click partial payment @Khadeeejah

**Comment by MeisterJustice** [comment]
@Khadeeejah you added partial payment as a sub menu for transfers. Is that how it's supposed to be?

**Review by MeisterJustice — CHANGES_REQUESTED** [review]
Please check comments

**Comment by Khadeeejah** [comment]
@MeisterJustice, I'm not sure I understand. Which deployment preview are you looking at?

This is the most recent and final one - https://lazerpay-documentation-v2-8o58xtxqn-lazerpay.vercel.app/

**Comment by MeisterJustice** [comment]
> https://lazerpay-documentation-v2-8o58xtxqn-lazerpay.vercel.app/

cool. When you are here [https://lazerpay-documentation-v2-8o58xtxqn-lazerpay.vercel.app/docs/payments/get-started](https://lazerpay-documentation-v2-8o58xtxqn-lazerpay.vercel.app/docs/payments/get-started) and you click on partial payment, to doesn't take you to the page you worked on

**Comment by Khadeeejah** [comment]
@MeisterJustice  kindly check the latest deployment,  here https://lazerpay-documentation-v2-bgncxs69g-lazerpay.vercel.app/docs/payments/get-started

i have fixed the routing

**Review by Frontend-io — APPROVED** [review]

**Pull request merged**
